// <auto-generated />
using System;
using GameStore_2._0.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore_2._0.Migrations
{
    [DbContext(typeof(GameStoreDbContext))]
    partial class GameStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("GameStore_2._0.DBModels.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.CartPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("GameId");

                    b.ToTable("CartPositions");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClickCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("CrslImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scr_Thumb")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ScreenImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Trailer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Trailer_Thumb")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClickCount = 0,
                            CoverImg = "/images/bg3/cover.jpg",
                            CrslImg = "/images/bg3/crsl.jpg",
                            Description = "Baldur's Gate 3 — это захватывающая ролевая игра от Larian Studios, вдохновлённая классическими системами Dungeons & Dragons. Действие разворачивается в легендарном мире Forgotten Realms, где вам предстоит возглавить уникальную группу героев и принять участие в эпической борьбе, затрагивающей судьбы всего Фаэруна.  \r\n\r\nСюжет начинается с похищения вашего героя иллитидом, который заражает его смертельно опасной личинкой. Ваша цель — найти способ остановить превращение и сохранить человечность, сталкиваясь с древними магиями, могущественными врагами и сложными моральными дилеммами.  \r\n\r\nBaldur's Gate 3 предлагает богатый открытый мир, где каждое ваше действие имеет значение. Вас ждут глубокие диалоги, сложные тактические сражения, использование правил D&D 5-й редакции и полная свобода в исследованиях. Уникальные спутники с собственными историями и мотивацией будут сопровождать вас в этом путешествии, а ваша связь с ними станет важной частью приключения.  \r\n\r\nСоздайте собственного героя, выбирая из множества рас и классов, или начните игру за одного из проработанных персонажей. Проходите сюжет в одиночку или с друзьями в кооперативном режиме до четырёх игроков. Взаимодействуйте с миром и его жителями так, как пожелаете, и откройте неожиданные тайны.  \r\n\r\nЭто история о судьбе, магии и выборе. Сможете ли вы спасти себя и мир, или погрузитесь в хаос и разрушение? Ваши решения определят всё.",
                            Genres = "[1]",
                            Price = 2000m,
                            Scr_Thumb = "/images/bg3/scr_thumb.jpg",
                            ScreenImg = "[\"/images/bg3/scr1.jpg\",\"/images/bg3/scr2.jpg\",\"/images/bg3/scr3.jpg\"]",
                            Title = "Baldur's Gate 3",
                            Trailer = "https://www.youtube.com/embed/1T22wNvoNiU?si=UyFarE5lI2JIhGDf",
                            Trailer_Thumb = "https://img.youtube.com/vi/1T22wNvoNiU/sddefault.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ClickCount = 0,
                            CoverImg = "/images/cyberpunk/cover.jpg",
                            CrslImg = "/images/cyberpunk/crsl1.jpg",
                            Description = "Cyberpunk 2077 — это захватывающая ролевая игра в жанре научной фантастики от CD Projekt Red. Действие игры разворачивается в мрачном и высокотехнологичном мире Найт-Сити, где корпорации правят, технологии диктуют жизнь, а опасности подстерегают на каждом шагу.  \r\n\r\nВы играете за Ви — наёмника, который стремится обрести бессмертие, став обладателем уникального биочипа. Ваша история — это путь в мир, полный интриг, насилия и моральных выборов. Сюжет развивается в зависимости от вашего стиля игры и решений, которые вы принимаете, открывая множество альтернативных концовок.  \r\n\r\nИгра предлагает впечатляющий уровень детализации: от ярких улиц Найт-Сити, наполненных неоном и хаосом, до глубоко проработанных персонажей. Вы можете выбрать происхождение героя, кастомизировать внешность, развивать навыки и адаптировать стиль игры под себя.  \r\n\r\nСражайтесь с корпорациями, исследуйте мрачные тайны города, занимайтесь взломом систем, улучшайте своё тело с помощью имплантов и создавайте свою легенду. В открытом мире вас ждут динамичные перестрелки, погружение в мрачные истории и разнообразные активности, от гонок до выполнения сложных миссий.  \r\n\r\nCyberpunk 2077 — это не просто игра, а целая вселенная, где технологии стирают границы возможного, а ваш выбор влияет на всё. Готовы ли вы погрузиться в будущее, где мечты сбываются, а за ними стоит высокая цена?",
                            Genres = "[1,2]",
                            Price = 2000m,
                            Scr_Thumb = "/images/cyberpunk/scr_thumb.jpg",
                            ScreenImg = "[\"/images/cyberpunk/scr1.jpg\",\"/images/cyberpunk/scr2.jpg\",\"/images/cyberpunk/scr3.jpg\"]",
                            Title = "Cyberpunk 2077",
                            Trailer = "https://www.youtube.com/embed/8X2kIfS6fb8?si=jGCvw1k4EpEScSJq",
                            Trailer_Thumb = "https://img.youtube.com/vi/8X2kIfS6fb8/sddefault.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ClickCount = 0,
                            CoverImg = "/images/disco/cover.jpg",
                            CrslImg = "/images/disco/crsl.jpg",
                            Description = "Disco Elysium — уникальная ролевая игра, созданная студией ZA/UM, которая сочетает в себе глубокую историю, необычную механику и художественный стиль. Действие происходит в мрачном городке Ревашоль, где вас ждёт мир, полный социальных конфликтов, политических интриг и личных трагедий.  \r\n\r\nВы берёте на себя роль детектива, который начинает расследование загадочного убийства. Однако есть одна проблема: ваш герой страдает от амнезии и алкоголизма, что делает каждый шаг на пути к истине непростым. Вас ждёт исследование не только места преступления, но и внутреннего мира вашего персонажа.  \r\n\r\nDisco Elysium предлагает невероятно проработанную систему диалогов, где вы можете взаимодействовать не только с другими персонажами, но и с различными сторонами своей личности. Каждое ваше решение и каждая реплика формируют уникальный путь и открывают новые возможности.  \r\n\r\nМир игры богат деталями: множество персонажей с уникальными историями, политические идеологии, которые вы можете поддерживать или отвергать, и запутанные моральные дилеммы. Всё это подчёркнуто атмосферным саундтреком и великолепным визуальным стилем.  \r\n\r\nЭто игра о сложных вопросах, личных сражениях и поиске смысла в хаосе. Какой детектив вы станете — принципиальным профессионалом, отчаянным циником или мечтателем, потерявшимся в философских раздумьях? Выбор за вами.",
                            Genres = "[1]",
                            Price = 1000m,
                            Scr_Thumb = "/images/disco/scr_thumb.jpg",
                            ScreenImg = "[\"/images/disco/scr1.jpg\",\"/images/disco/scr2.jpg\",\"/images/disco/scr3.jpg\"]",
                            Title = "Disco Elysium",
                            Trailer = "https://www.youtube.com/embed/P-UY6IyI03Q?si=S6Y9JAImFebvi5Jc",
                            Trailer_Thumb = "https://img.youtube.com/vi/P-UY6IyI03Q/sddefault.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ClickCount = 0,
                            CoverImg = "/images/fallout4/cover.jpg",
                            CrslImg = "/images/fallout4/crsl1.jpg",
                            Description = "Fallout 4 — культовая ролевая игра от Bethesda Game Studios, действие которой разворачивается в постапокалиптическом мире, разрушенном ядерной войной. Игра переносит вас в разорённые земли Содружества, где каждое решение влияет на ваше выживание и судьбу окружающего мира.  \r\n\r\nВы играете за жителя Убежища 111, который выходит на поверхность спустя 200 лет после ядерного апокалипсиса, чтобы найти своего похищенного сына. Мир полон опасностей: от мутантов и рейдеров до загадочных институтов и фракций, каждая из которых имеет свои цели и взгляды на восстановление цивилизации.  \r\n\r\nFallout 4 предлагает огромный открытый мир с бесчисленными возможностями для исследования. Вы можете строить свои поселения, модифицировать оружие и броню, взаимодействовать с местными фракциями и находить неожиданные сюжеты за каждым углом.  \r\n\r\nСистема S.P.E.C.I.A.L. позволяет кастомизировать персонажа, определяя его способности и стиль игры. Вас ждут напряжённые сражения, глубокие диалоги и сложные моральные выборы, которые определяют, каким будет будущее Содружества.  \r\n\r\nFallout 4 — это история о выживании, утрате и надежде. Как выстроить новую жизнь среди руин старого мира? Это зависит только от вас.",
                            Genres = "[1,2]",
                            Price = 800m,
                            Scr_Thumb = "/images/fallout4/scr_thumb.jpg",
                            ScreenImg = "[\"/images/fallout4/scr1.jpg\",\"/images/fallout4/scr2.jpg\",\"/images/fallout4/scr3.jpg\"]",
                            Title = "Fallout 4",
                            Trailer = "https://www.youtube.com/embed/X5aJfebzkrM?si=lMdWkj0k_R61Rsos",
                            Trailer_Thumb = "https://img.youtube.com/vi/X5aJfebzkrM/sddefault.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ClickCount = 0,
                            CoverImg = "/images/forza/cover.jpg",
                            CrslImg = "/images/forza/crsl1.jpg",
                            Description = "Forza Horizon 5 — великолепная гоночная игра от Playground Games, которая предлагает игрокам отправиться в живописный и детально проработанный открытый мир, вдохновлённый разнообразными пейзажами Мексики. Это самая масштабная и визуально впечатляющая часть в серии, сочетающая реалистичную физику с элементами аркадного веселья.  \r\n\r\nВас ждёт более 500 автомобилей, каждый из которых можно настроить под свой стиль вождения. От культовых спортивных машин до внедорожников и экзотических суперкаров — Forza Horizon 5 предлагает что-то для каждого. Разнообразие гонок включает в себя уличные заезды, ралли и экстремальные трюки.  \r\n\r\nИгровой мир удивляет своей красотой и масштабом: от пустынь и джунглей до вулканов и исторических городов. Благодаря смене времён года каждая гонка выглядит уникально, а динамическая погода создаёт неожиданные вызовы.  \r\n\r\nИгра наполнена активностями и событиями, от сетевых соревнований с друзьями до одиночных испытаний и эпичных фестивалей. Кампания позволяет вам стать легендой Horizon, участвуя в крупнейшем автомобильном шоу мира.  \r\n\r\nForza Horizon 5 — это идеальное сочетание скорости, свободы и красоты. Откройте для себя мир без границ, где каждая гонка — это новое приключение.",
                            Genres = "[3]",
                            Price = 2000m,
                            Scr_Thumb = "/images/forza/scr_thumb.jpg",
                            ScreenImg = "[\"/images/forza/scr1.jpg\",\"/images/forza/scr2.jpg\",\"/images/forza/scr3.jpg\"]",
                            Title = "Forza Horizon 5",
                            Trailer = "https://www.youtube.com/embed/FYH9n37B7Yw?si=oF7rOSpHwHPiH5oN",
                            Trailer_Thumb = "https://img.youtube.com/vi/FYH9n37B7Yw/sddefault.jpg"
                        },
                        new
                        {
                            Id = 6,
                            ClickCount = 0,
                            CoverImg = "/images/poe2/cover.jpg",
                            CrslImg = "/images/poe2/crsl.jpg",
                            Description = "Path of Exile 2 — это продолжение легендарной action-RPG от Grinding Gear Games, которое обещает ещё больше глубины, вызовов и разнообразия. Игра сохраняет мрачный тон оригинала, расширяя его новыми механиками и историями, которые разворачиваются спустя 20 лет после событий первой части.  \r\n\r\nPath of Exile 2 предлагает полностью переработанную кампанию из семи актов, которая идёт параллельно с оригинальной сюжетной линией. Игроки могут исследовать новый мир, где враги стали ещё умнее, а битвы — более динамичными. Визуальные эффекты и анимации значительно улучшены, что делает каждую способность зрелищной и мощной.  \r\n\r\nГлавная особенность — новая система пассивных умений и улучшенные драгоценные камни навыков. Теперь гнёзда напрямую связаны с экипировкой, что открывает ещё больше возможностей для уникальных билдов. Игроки смогут экспериментировать с 19 новыми архетипами классов, сохраняя доступ к старым вариантам из оригинальной игры.  \r\n\r\nPath of Exile 2 сохраняет ключевые аспекты серии: сложность, огромное древо навыков, масштабные эндгейм-события и постоянное развитие. Игра остаётся бесплатной, предлагая тонны контента без необходимости платить за победу.  \r\n\r\nЭто идеальное продолжение для преданных фанатов и отличная точка входа для новых игроков, желающих испытать мрачный и богатый мир Path of Exile.",
                            Genres = "[1]",
                            Price = 500m,
                            Scr_Thumb = "/images/poe2/scr_thumb.jpg",
                            ScreenImg = "[\"/images/poe2/scr1.jpg\",\"/images/poe2/scr2.jpg\",\"/images/poe2/scr3.jpg\"]",
                            Title = "Path of Exile 2",
                            Trailer = "https://www.youtube.com/embed/QpbGfihd0_Q?si=qIOOoGKMSF-gnlgT",
                            Trailer_Thumb = "https://img.youtube.com/vi/QpbGfihd0_Q/sddefault.jpg"
                        },
                        new
                        {
                            Id = 7,
                            ClickCount = 0,
                            CoverImg = "/images/silenthill/cover.jpg",
                            CrslImg = "/images/silenthill/crsl1.jpg",
                            Description = "Silent Hill 2 Remake — переосмысленная версия культовой психологической хоррор-игры от Bloober Team и Konami, которая переносит классическую историю в современную графическую и технологическую эпоху. Эта игра возвращает игроков в зловещий город Сайлент Хилл, где кошмары оживают, а грань между реальностью и иллюзией стирается.  \r\n\r\nВ центре сюжета — Джеймс Сандерленд, получивший письмо от своей покойной жены Мэри, которая зовёт его в Сайлент Хилл. Погрузившись в город, он сталкивается с искалеченными монстрами, загадочными персонажами и туманной атмосферой, которая становится отражением его подавленных чувств и тёмных тайн.  \r\n\r\nRemake обновляет оригинал, используя мощь Unreal Engine 5, чтобы передать мельчайшие детали города, устрашающих существ и эмоции персонажей. В игре полностью переработаны модели, анимации и освещение, что усиливает атмосферу страха и безысходности.  \r\n\r\nРазработчики добавили современные элементы управления, улучшили боевую систему и адаптировали звуковое сопровождение под новые технологии. Музыка от Акиры Ямаоки и обновлённая озвучка персонажей усиливают эмоциональную вовлечённость.  \r\n\r\nSilent Hill 2 Remake сохраняет дух оригинала, но предлагает свежий взгляд на один из величайших хорроров в истории. Эта игра приглашает как давних фанатов, так и новых игроков погрузиться в пугающий и незабываемый опыт путешествия в глубины человеческого сознания.",
                            Genres = "[5]",
                            Price = 2000m,
                            Scr_Thumb = "/images/silenthill/scr_thumb.jpg",
                            ScreenImg = "[\"/images/silenthill/scr1.jpg\",\"/images/silenthill/scr2.jpg\",\"/images/silenthill/scr3.jpg\"]",
                            Title = "Silent Hill 2",
                            Trailer = "https://www.youtube.com/embed/pyC_qiW_4ZY?si=CLiHsguU7kyPF-ch",
                            Trailer_Thumb = "https://img.youtube.com/vi/pyC_qiW_4ZY/sddefault.jpg"
                        },
                        new
                        {
                            Id = 8,
                            ClickCount = 0,
                            CoverImg = "/images/starfield/cover.jpg",
                            CrslImg = "/images/starfield/crsl1.jpg",
                            Description = "Starfield — это долгожданная RPG от Bethesda Game Studios, предлагающая игрокам исследовать бескрайние просторы космоса. Это первая новая игровая вселенная студии за последние 25 лет, сочетающая в себе масштаб и детализацию, которыми славятся их проекты, с уникальной атмосферой космических приключений.  \r\n\r\nСюжет разворачивается в 2330 году, когда человечество колонизировало множество планет и звёздных систем. Вы становитесь членом \"Созвездия\" — организации исследователей, которая занимается поиском ответов на самые глубокие загадки вселенной. Игроки смогут свободно перемещаться по тысячам планет, обживать далекие уголки галактики и взаимодействовать с многочисленными фракциями, каждая из которых имеет свои цели и ценности.  \r\n\r\nИгра предлагает глубоко проработанную систему кастомизации персонажа и корабля. Вы можете не только настроить внешность и навыки своего героя, но и построить уникальный звездолёт, подходящий под ваш стиль игры — от дипломатического исследователя до опасного космического пирата.  \r\n\r\nБоевая система включает перестрелки в космосе и на планетах, а также схватки на ближних дистанциях. Важным элементом игры являются исследования: на планетах вы можете собирать ресурсы, строить базы и разгадывать таинственные артефакты, которые влияют на ход всей истории.  \r\n\r\nStarfield — это беспрецедентный по масштабам и возможностям проект, который переносит классические механики Bethesda в совершенно новый космический антураж. Игра предлагает богатый сюжет, захватывающие приключения и свободу, о которой мечтают поклонники научной фантастики.",
                            Genres = "[1,2]",
                            Price = 3000m,
                            Scr_Thumb = "/images/starfield/scr_thumb.jpg",
                            ScreenImg = "[\"/images/starfield/scr1.jpg\",\"/images/starfield/scr2.jpg\",\"/images/starfield/scr3.jpg\"]",
                            Title = "Starfield",
                            Trailer = "https://www.youtube.com/embed/Ek3I6_9c58E?si=2rbnk7_NtQbFTIcC",
                            Trailer_Thumb = "https://img.youtube.com/vi/Ek3I6_9c58E/sddefault.jpg"
                        },
                        new
                        {
                            Id = 9,
                            ClickCount = 0,
                            CoverImg = "/images/tekken8/cover.jpg",
                            CrslImg = "/images/tekken8/crsl.jpg",
                            Description = "Tekken 8 — это последняя часть легендарной серии файтингов от Bandai Namco, продолжение знаменитой истории о борьбе между участниками жестокого турнира и их судьбах, переплетенных с темными семейными тайнами. В Tekken 8 игроков ожидает еще больше динамичных боев, улучшенная графика, новые персонажи и возвращение знакомых бойцов.\r\n\r\nИгровой процесс сохранил традиционное для Tekken сочетание стратегии и экшен-элементов, с возможностью комбинировать различные удары, защитные маневры и специальные приемы. В новом издании особое внимание уделено зрелищным финальным атакам, а также обновленному балансу персонажей.\r\n\r\nСреди нововведений — улучшенная система AI, которая делает противников умнее и непредсказуемее, и различные режимы игры, включая как одиночные кампании, так и многопользовательские бои. Каждый бой в Tekken 8 — это уникальный опыт, где решается не только мастерство, но и личная сила воли.\r\n\r\nTekken 8 продолжает традиции серии, предлагая фанатам как новые возможности для самовыражения, так и более глубокие механики для опытных игроков, желающих освоить каждый уголок игры.",
                            Genres = "[4]",
                            Price = 2000m,
                            Scr_Thumb = "/images/tekken8/scr_thumb.jpg",
                            ScreenImg = "[\"/images/tekken8/scr1.jpg\",\"/images/tekken8/scr2.jpg\",\"/images/tekken8/scr3.jpg\"]",
                            Title = "Tekken 8",
                            Trailer = "https://www.youtube.com/embed/_MM4clV2qjE?si=iPeLufVnaC6LaQ9j",
                            Trailer_Thumb = "https://img.youtube.com/vi/_MM4clV2qjE/sddefault.jpg"
                        },
                        new
                        {
                            Id = 10,
                            ClickCount = 0,
                            CoverImg = "/images/warthunder/cover.jpg",
                            CrslImg = "/images/warthunder/crsl1.jpg",
                            Description = "War Thunder — это многопользовательская военная онлайн-игра, которая предлагает игрокам участвовать в эпичных битвах с использованием разнообразной техники, включая авиацию, бронетехнику и корабли, в сражениях различных исторических эпох. Игра объединяет реализм и динамичный игровой процесс, предоставляя широкие возможности для стратегического планирования и боевых действий.\r\n\r\nВ War Thunder игроки могут погружаться в крупномасштабные сражения на различных фронтах Второй мировой войны, а также в более современные конфликты, управляя как исторической техникой, так и современными боевыми машинами. Игра предлагает разнообразные режимы, от аркадных боев до более реалистичных и симуляционных матчей.\r\n\r\nСистема прогрессии позволяет игрокам улучшать свою технику, открывая новые модули, оружие и улучшения, что даёт возможность адаптироваться к различным стилям игры. Разнообразие карт, техники и режимов создают уникальную атмосферу и делают каждую битву неповторимой.\r\n\r\nWar Thunder продолжает развиваться, предлагая новые обновления с техникой и картами, что делает её одной из самых популярных и масштабных военных онлайн-игр в мире.",
                            Genres = "[2]",
                            Price = 5000m,
                            Scr_Thumb = "/images/warthunder/scr_thumb.jpg",
                            ScreenImg = "[\"/images/warthunder/scr1.jpg\",\"/images/warthunder/scr2.jpg\",\"/images/warthunder/scr3.jpg\"]",
                            Title = "War Thunder",
                            Trailer = "https://www.youtube.com/embed/miVz9nsMYEw?si=Fiq-hMRfU2P9ntwj",
                            Trailer_Thumb = "https://img.youtube.com/vi/miVz9nsMYEw/sddefault.jpg"
                        },
                        new
                        {
                            Id = 11,
                            ClickCount = 0,
                            CoverImg = "/images/wow/cover.jpg",
                            CrslImg = "/images/wow/crsl1.jpg",
                            Description = "World of Warcraft: War Within — это захватывающее дополнение к легендарной MMORPG от Blizzard Entertainment, которое погружает игроков в эпическое столкновение сил в условиях разрушительного внутреннего конфликта. В этой главе мира Азерота открываются новые горизонты борьбы, и в центре событий оказываются самые могущественные фракции, готовые к решающим битвам.\r\n\r\nДополнение \"War Within\" фокусируется на разрушительном конфликте внутри ключевых народов Азерота. Игрокам предстоит принять участие в сражениях, которые потрясут основы мира, где старые альянсы разрушаются, а новые вражды вспыхивают с небывалой силой. В новой истории игроки смогут исследовать неожиданные сюжетные повороты, раскрывая тайны о предательстве, борьбе за власть и угрозах, которые исходят от самых неожиданных источников.\r\n\r\nДополнение включает в себя новые зоны, подземелья и рейды, которые открывают новые возможности для исследования и сражений. Также будут добавлены новые расы, классы и возможности кастомизации персонажей, позволяя игрокам погрузиться в мир с еще большей глубиной.\r\n\r\nWorld of Warcraft: War Within — это эпическая глава, которая подарит игрокам невероятные приключения, новые испытания и незабываемые моменты в любимом мире Азерота.",
                            Genres = "[1]",
                            Price = 8000m,
                            Scr_Thumb = "/images/wow/scr_thumb.jpg",
                            ScreenImg = "[\"/images/wow/scr1.jpg\",\"/images/wow/scr2.jpg\",\"/images/wow/scr3.jpg\"]",
                            Title = "World Of Warcraft: War Within",
                            Trailer = "https://www.youtube.com/embed/o03STclgxSc",
                            Trailer_Thumb = "//img.youtube.com/vi/o03STclgxSc/mqdefault.jpg"
                        });
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivationKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OrderCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.OrderPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPositions");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BuySum")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.WishlistGame", b =>
                {
                    b.Property<Guid>("WishlistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("TEXT");

                    b.HasKey("WishlistId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("WishlistGames");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Cart", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.CartPosition", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.Cart", "Cart")
                        .WithMany("Positions")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore_2._0.DBModels.Game", "Game")
                        .WithMany("CartPositions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Order", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.OrderPosition", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore_2._0.DBModels.Order", "Order")
                        .WithMany("OrderPositions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Wishlist", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.WishlistGame", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.Game", "Game")
                        .WithMany("WishlistGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore_2._0.DBModels.Wishlist", "Wishlist")
                        .WithMany("WishlistGames")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore_2._0.DBModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GameStore_2._0.DBModels.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Cart", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Game", b =>
                {
                    b.Navigation("CartPositions");

                    b.Navigation("WishlistGames");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Order", b =>
                {
                    b.Navigation("OrderPositions");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.User", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GameStore_2._0.DBModels.Wishlist", b =>
                {
                    b.Navigation("WishlistGames");
                });
#pragma warning restore 612, 618
        }
    }
}
